services:
  - type: web
    name: westlotto-scraper
    env: python
    buildCommand: pip install -r requirements.txt
    repo: https://github.com/gitMatthias/ottopipe
    branch: main
    autoDeploy: true
